query {
  allSemesters(orderBy: "yearJewish,name") {
    edges {
      node {
        id
        name
        yearJewish
      }
    }
  }
  allStaff(orderBy: "lastName,firstName") {
    edges {
      node {
        id
        title
        firstName
        lastName
      }
    }
  }
  allCourses(orderBy: "name") {
    edges {
      node {
        id
        name
      }
    }
  }
  allFeedbackForms(orderBy: "timeCreated,label") {
    edges {
      node {
        id
        label
      }
    }
  }
}