query {
  allGrades {
    edges {
      node {
        id
        moed
        average
        histogram
        approved
        uploader {
          firstName
          lastName
        }
        courseSemester {
          id
          course {
            name
          }
          semester {
            name
            yearJewish
          }
        }
      }
    }
  }
}