query {
  allStaff {
    edges {
      node {
        id
        firstName
        lastName
        title
        averageRatingAsLecturer
        averageRatingAsTeachingAssistant
        units {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}