query($search: String!, $first: Int!, $after: String, $orderBy: String) {
  allStaff(search: $search, first: $first, after: $after, orderBy: $orderBy) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        id
        firstName
        lastName
        title
        averageRatingAsLecturer
        averageRatingAsTeachingAssistant
        units {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}