query ($after: String!, $perPage: Int!, $keywords: String!, $role: String!) {
  allUsers(after: $after, first: $perPage, fullName_Icontains: $keywords, role: $role, orderBy: "lastName,firstName") {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        firstName
        lastName
        role
        createdDate
        email
        isVerified
      }
    }
  }
}