query courseSemesterDetails($id: ID!){
  courseSemesterDetails(id: $id) {
    course {
      id
      name
    }
    semester {
      id
      name
      yearJewish
    }
    coursesemesterstaffSet {
      edges {
        node {
          lecturers {
            edges {
              node {
                id
                title
                firstName
                lastName
              }
            }
          }
          teachingAssistants {
            edges {
              node {
                id
                title
                firstName
                lastName
              }
            }
          }
        }
      }
    }
    feedbackformcoursesemesterSet {
      edges {
        node {
          feedbackForm {
            id
            label
          }
        }
      }
    }
  }
}