query currentSemesterCourses($keywords: String!, $rowsPerPage: Int!, $after: String!, $tags: [ID], $compulsory: Boolean, $isCurrent: Boolean) {
  allCourses(orderBy: "name", name_Icontains: $keywords, first: $rowsPerPage, after: $after, tags: $tags, compulsory: $compulsory) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        name
        coursesemesterSet(orderBy: "-semesterYearJewish,-semesterName", semester_IsCurrent: $isCurrent) {
          edges {
            node {
              id
              semester {
                name
                yearJewish
              }
              coursesemesterstaffSet {
                edges {
                  node {
                    lecturers {
                      edges {
                        node {
                          title
                          firstName
                          lastName
                        }
                      }
                    }
                    teachingAssistants {
                      edges {
                        node {
                          title
                          firstName
                          lastName
                        }
                      }
                    }
                  }
                }
              }
              averageLecturerRating
              averageTeachingAssistantRating
              averageCourseRating
            }
          }
        }
      }
    }
  }
}