query editCourseDetails($id: ID!) {
  courseDetails(id: $id) {
    name
    unit {
      id
      name
    }
    courseType
    compulsory
    points
    classification
    prerequisites {
      edges {
        node {
          id
          name
        }
      }
    }
    tags {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}