query {
  myFeedbacks {
    edges {
      node {
        id
        averageCourseRating
        averageLecturerRating
        averageTeachingAssistantRating
        courseSemester {
          id
          course {
            name
          }
          semester {
            name
            yearJewish
          }
        }
        feedback {
          id
        }
      }
    }
  }
}