mutation newUser($email: String!, $password: String!, $firstName: String, $lastName: String) {
  newUser (input: {
    email: $email
    password: $password
    firstName: $firstName
    lastName: $lastName
  }) {
    user {
      id
    }
  }
}