query semesterFeedbacks($id: ID!) {
  feedbackFormCourseSemester(id: $id) {
    feedbackForm {
      id
      questionfeedbackSet {
        edges {
          node {
            question {
              id
              question
              classification
            }
          }
        }
      }
    }
  }
  myFeedbacks {
    edges {
      node {
       questionuserfeedbackSet {
        edges {
          node {
            question {
              id
            }
            ranking
            userFeedback {
              feedback {
                id
              }
            }
          }
        }
      }
      }
    }
  }
}