mutation updateUser($id: String!, $email: String!, $password: String!, $firstName: String, $lastName: String) {
  updateUser (input: {
    id: $id
    email: $email
    password: $password
    firstName: $firstName
    lastName: $lastName
  }) {
    user {
      id
    }
  }
}