query ($id: ID!){
  userFeedback(id: $id) {
    id
    courseSemester {
      coursesemesterstaffSet {
        edges {
          node {
            lecturers {
              edges {
                node {
                  id
                  firstName
                  lastName
                  title
                }
              }
            }
            teachingAssistants {
              edges {
                node {
                  id
                  firstName
                  lastName
                  title
                }
              }
            }
          }
        }
      }
    }
    questionuserfeedbackSet {
      edges {
        node {
          question {
            id
            question
            classification
          }
          ranking
        }
      }
    }
    commentSet {
      edges {
        node {
          id
          authorName
          content
          canEdit
        }
      }
    }
    generalFeedback
    lecturerFeedback
    teachingAssistantFeedback
    likesCount
    dislikesCount
    myFeedback
    liked
    disliked
  }
}